### ISSUE TITLE
After writting a comment it redirets back to the base link and not the current page link

### ISSUE THREAD

**Issue by adrian-stein** [silverstripe/silverstripe-comments#124]
I have comments on a custom page type and when I finish leaving a comment it redirects back to the parent link. This works fine except for the fact that I am viewing my comments on an action of the page so "site_root/course_page/view_comments" instead of just "site_root/course_page" ( base page link). When the comment is left it then redirects away from my comments action directly to the base link of the page and not the action I was currently on. I tried to extend the "doPostComment" method which performs the redirect but I could not. Are you able to allow this or even better redirect to action if there is one or even the current URL?

The code in question is in the if statement on line 560 of the CommentingController, under the 'Find parent link' comment and it runs the code $url = $parent->Link();

**Comment by adrian-stein** [comment]
I have found a way to work around it by using  'alterCommentForm($form)' and putting it as an Extension and adding a hidden field to the form with the URL I need to return to. Then the if(!empty($data['ReturnURL']))  check does the redirect I need.

**Comment by dhensby** [comment]
Is this resolved?

**Comment by adrian-stein** [comment]
Hey. Not sure yet. I need to test. Currently on a cruise so cant get to work stuff. Will check when I get back!!!

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
