### ISSUE TITLE
Make Comments Cachable With Respect to Time

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#127]
In the template https://github.com/silverstripe/silverstripe-comments/blob/master/templates/CommentsInterface_singlecomment.ss line 8 effectively means the default templates cannot be cached

```
<span class="date">$Created.Nice ($Created.Ago)</span>
```

The value of $Created.Ago will obviously change over time.

Perhaps a better solution would be to use absolute values for non JavaScript, and then use a jquery plugin such as http://www.jplugins.net/jquery-timeago/ or http://mattbradley.github.io/livestampjs/ for minutes/hours/days ago functionality.

I guess there is the thorny issue of i18n to deal with, momentjs which the latter plugin uses appears equipped for this http://momentjs.com/docs/#/i18n/

One possibility may be to introduce another configuration option that defaults to the current functionality, but allows for the functionality above to be turned on.

**Comment by gordonbanderson** [comment]
This is working for me locally bar 2 caveats, as such not yet presented as a pull request.
* I need to set up SCSS to CSS generation locally.  Whilst I've used compass standalone I will need to read up on how it integrates with SilverStripe.
* How best to deal with locales?  The method jquery.timeago.js uses is to include another JavaScript file overriding some text, see https://github.com/gordonbanderson/silverstripe-comments/blob/issue_157_wip/code/extensions/CommentsExtension.php#L428 for a commented out example for Thai.  Whilst I have not double checked I'd imagine there is not a 1 to 1 mapping between the locales available in SilverStripe and those for the addon.  Perhaps the best option is to take say the `th` part of `th_TH` and check for the relevant file existing, if it does not fall back to English?

**Comment by gordonbanderson** [comment]
I forgot the branch with the changes is this one https://github.com/gordonbanderson/silverstripe-comments/tree/issue_157_wip

**Comment by tractorcow** [comment]
> How best to deal with locales?

You can get the locale from `ss.i18n.getLocale()` in JS i think. If you need PHP conditional for locale-specific script includes, check out Requirements_Backend::add_i18n_javascript() for some logic you can probably duplicate. It goes through a list of candidates from most specific (full locale) to least specific (lang only, current locale, default locale, etc).

**Comment by gordonbanderson** [comment]
Thanks, that sounds like the kind of info I was looking for

**Comment by gordonbanderson** [comment]
I eventually opted not to check files on the file system but create config (via a Ruby script) for the valid list of locales available in TimeAgo library.  If the locale from SilverStripe does not exist in TimeAgo, it defaults back to English.

**Comment by gordonbanderson** [comment]
Further musing on this.  I think the TimeAgo functionality should be installed via composer as it's not only the comments that need this, but the forums and blog module.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
