### ISSUE TITLE
What is the expected behaviour of odd and even css classes with nested comments?

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#128]
When comments are nested, the list of replies to a comment resets to begging with odd, meaning that if say an odd comment is replied to there are 2 odd comments in a row in the output.  i.e. something of this nature:

```html
<ul class="comments-list">
<li class="comment odd">
  <ul class="comments-list">
    <li class="comment odd"
```

**Comment by tractorcow** [comment]
It only counts the order in that particular level. ;)

having a global striping mechanism will probably need some kind of additional template provider. Check out SSViewer_BasicIteratorSupport for an example implementation. You could probably add one that does what you want in user code.

**Comment by tractorcow** [comment]
I'm going to close this since this is an answered question. :)
