### ISSUE TITLE
ProvideComments doesn't honor $defaults in model

### ISSUE THREAD

**Issue by jyrkij** [silverstripe/silverstripe-comments#130]
An example of this is in [silverstripe-blog](https://github.com/silverstripe/silverstripe-blog). It [defines](https://github.com/silverstripe/silverstripe-blog/blob/27611c980dfd203b617a78c567c01537e737d53c/code/model/Blog.php#L75-77) `ProvideComments` as false in `$defaults` yet on creation it is true and checked. I believe this is due to [this line](https://github.com/silverstripe/silverstripe-comments/blob/138bbbfd843f7c01f4bf6a7ee8b88f259b0f5b58/code/extensions/CommentsExtension.php#L82):

    $this->owner->ProvideComments = $this->owner->getCommentsOption('enabled') ? 1 : 0;

How could this take into account wether the model itself sets ProvideComments or not?

**Comment by tractorcow** [comment]
I think we should change that line so that the extension only set this if the model hasn't assigned it.

```php
// Set default if not provided by model
if(!isset($this->owner->ProvideComments)) {
	$this->owner->ProvideComments = $this->owner->getCommentsOption('enabled') ? 1 : 0;
}
```

**Comment by tractorcow** [comment]
Seems like a bit more work was necessary.

See https://github.com/silverstripe/silverstripe-comments/pull/136
