### ISSUE TITLE
Gravatar CSS Needs Fixing

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#158]
Out of the box with the default Simple theme and config as per docs/en/Configuration.md the layout is somewhat off.  See attached image.
![gravatarcomments](https://cloud.githubusercontent.com/assets/7060/12912630/67e39af8-cf4c-11e5-8ffa-3c881fa6a0c6.png)

**Comment by tractorcow** [comment]
Maybe CSS the gravitar so it's tiny by default? (i.e. line height)?

**Comment by gordonbanderson** [comment]
Either that or move it elsewhere.  Tried to fix it last night but life got in the way :(

**Comment by tractorcow** [comment]
@scott1702 what do you think about gravitars?
