### ISSUE TITLE
Comment Header Missing Visually After Posting a Comment

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#159]
This is happening for me for both initial comment posting and replies.  The URL posted to is of the form `contact-us/#comment-9` which aligns the rendered page with a DOM element of `id="comment-0"`.  However this ID occurs below the comment header with the gravatar and 'posted by' info.  See attached images.

Form pre posting:
![form01](https://cloud.githubusercontent.com/assets/7060/12913454/64c405ec-cf51-11e5-94f0-305afd49a763.png)

New comment rendered after posting:
![form02](https://cloud.githubusercontent.com/assets/7060/12913456/6aa2258e-cf51-11e5-8a33-e8c9f7fc3f36.png)

What I reckon would be better to show:
![form03](https://cloud.githubusercontent.com/assets/7060/12913469/81de6dfc-cf51-11e5-99ca-8fbcff85c924.png)

**Comment by tractorcow** [comment]
fixed with #161
