### ISSUE TITLE
Ressurect AJAX Spam/Ham/Approve

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#162]
Just testing it appears this is still working for nested comments.

**Comment by tractorcow** [comment]
So if it works, do we need a bug ticket for it? :D

**Comment by gordonbanderson** [comment]
True...

**Comment by tractorcow** [comment]
Oh, it was removed... ok I understand the context now. :dancer: 

I'm sure I was the one who removed it, but I have no memory of the incident lol.

**Comment by gordonbanderson** [comment]
This is the relevant commit https://github.com/silverstripe/silverstripe-comments/commit/468df23801810985c5040ac850c0bd76b07a0cd0
