### ISSUE TITLE
Remove Line Numbers from Compass Output

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#163]
Currently the Compass config file is configured to output line numbers from the source scss file.  I see this as a problem for 2 reasons

1) Unecessary issues with merging
2) Larger than necessary CSS

**Comment by tractorcow** [comment]
Do you mean newlines, or literal line numbers?

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-comments/pull/164, I gotcha now. :D

**Comment by gordonbanderson** [comment]
Literal line numbers

**Comment by tractorcow** [comment]
Fixed with #164
