### ISSUE TITLE
Marking a comment as moderation redirect to URL ending in _PostCommentForm_error

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#168]
I initially though I was causing an error just by looking at the URL, when moderating a message.  This is not the case, and grepping the codebase the _PostCommentForm is not used elsewhere.  As such change it to something more relevant.

**Comment by gordonbanderson** [comment]
I have a fix for this but it alters the CSS also (moderation box needed love).  I will include it in a merged pull for what appears to be four issues altering the CSS.

**Comment by tractorcow** [comment]
Thanks for the fix. ;D
