### ISSUE TITLE
Multiple Reply Forms with JS Off

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#169]
When JavaScript is off a reply form is rendered for each and every comment making the comments tricky to read.  I think a 'Reply' button and a new action to render a reply form in the appropriate place would be better.  As an example, from a WordPress site, http://www.richardbarrow.com/2014/12/train-trip-to-the-sunflower-fields-in-thailand/

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
