### ISSUE TITLE
Improve Out of the Box Design, Especially With Nesting

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#171]
The current style with Gravatar and nesting on looks somewhat broken.
![commentoldstyle](https://cloud.githubusercontent.com/assets/7060/13027024/99eac63e-d271-11e5-9015-71b11412103c.png)

**Comment by gordonbanderson** [comment]
Work in progress, code can be found here https://github.com/gordonbanderson/silverstripe-comments/tree/commentfixeswithstyle
![commentsupdated](https://cloud.githubusercontent.com/assets/7060/13027029/b8a3f500-d271-11e5-947d-afcf3842c2d9.png)

**Comment by tractorcow** [comment]
Wow very pretty. :dancer: 

Might need to get our resident UX eyes over this. @flashbackzoo  / @scott1702  what do you think?

**Comment by scott1702** [comment]
Very nice indeed—want to PR @gordonbanderson?

**Comment by gordonbanderson** [comment]
Some of the other features I am fixing up need to fixed and merged in first.  I'll set up a live demo once ready.

**Comment by gordonbanderson** [comment]
Sticking with the theme button wise for reply
![wip](https://cloud.githubusercontent.com/assets/7060/13040415/599e4740-d3de-11e5-9d59-7c30c3743445.png)
