### ISSUE TITLE
Pagination Needs A Window of Pages

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#179]
I remembered I had an old site where the comment forms were open (but marked for moderation).  Just checking the database I had erm 1600 comments so I added them all to a single page for testing purposes.  Result, 160 pagination links :)

Should be a simple fix, I remember this is built in.
![commentlinks](https://cloud.githubusercontent.com/assets/7060/13080194/395249a6-d4fa-11e5-94c9-77dc36b56c9f.png)

**Comment by gordonbanderson** [comment]
Could possibly add more, this is the default
![spam002](https://cloud.githubusercontent.com/assets/7060/13081138/40f37eb0-d4fe-11e5-813d-6ab67436a867.png)

**Comment by tractorcow** [comment]
You can use the PaginationSummary() method to declare the number of pages you need.
