### ISSUE TITLE
Conflict when install with news-module 

### ISSUE THREAD

**Issue by tungdt-90** [silverstripe/silverstripe-comments#186]
I got a problem when i run "composer update" :

`PHP Fatal error:  Uncaught exception 'Exception' with message 'There are two files containing the "Comment" class: "/home/tung/www/boarding/comments/code/model/Comment.php" and "/home/tung/www/boarding/silverstripe-newsmodule/code/objects/Comment.php"' in /home/tung/www/boarding/framework/core/manifest/ClassManifest.php:569`

Currently i'm using this module: 

https://github.com/firesphere/silverstripe-newsmodule

And it also has a class called "Comment".

So does anyone have any fix for this ?

**Comment by dhensby** [comment]
Hi, this is an issue with the newsmodule as it has a class callled `Comment` which also exists in the comments module. 

You'll need to report the issue with newsmodule as either they need to rename that class or to swap out their comments system for this module

**Comment by dhensby** [comment]
Issue raised for you here: https://github.com/Firesphere/silverstripe-newsmodule/issues/169

**Comment by tungdt-90** [comment]
Ah ok, i will report on that module.

Sorry that i haven't made a deeper research before i ask.

**Comment by tractorcow** [comment]
We can namespace comments module in 4.0 :)
