### ISSUE TITLE
BUG: comment counters in CMS do not update upon comment deletion

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-comments#188]
After deleting a comment in the CMS, the Approved counter in the top right still shows an approved comment is present:

![screenshot from 2016-10-11 13 34 56](https://cloud.githubusercontent.com/assets/8912185/19255215/f994310c-8fb7-11e6-9b28-7c6c9f68d52a.png)

The counter updates correctly when page is refreshed.

**Comment by dhensby** [comment]
I'm going to say this is too minor an issue for now. It's not controlled by AJAX/JS and so making this change will be a lot of engineering to solve a problem that's not that big a deal.

Obviously we'd accept a PR for it, but I'm not seeing the effort/reward payback on this.

Even Reddit's inbox has this issue

**Comment by SpiritLevel** [comment]
Yup. I thought I would just make a quick note of this for when silverstripe-comments needs a bit of refactoring for SS4, which would be a good time to fix the problem. :)

**Comment by dhensby** [comment]
When we move to react this kind of thing may be easier

**Comment by wilr** [comment]
Retested on latest bulk editor and this number automatically updates.
