### ISSUE TITLE
BUG: Finnish translation for CommentsInterface_ss: Comments is still in English

### ISSUE THREAD

**Issue by Althegreat24** [silverstripe/silverstripe-comments#192]
Just installed the newest version of this module and spotted this little bug.
In lang/fi.yml 
  CommentsInterface_ss:
    COMMENTS: Comments

It should be 'Kommentit'

**Comment by dhensby** [comment]
translations are handled over at transifex: https://www.transifex.com/silverstripe/silverstripe-comments/dashboard/
