### ISSUE TITLE
No Behaviour Tab

### ISSUE THREAD

**Issue by digi-brains** [silverstripe/silverstripe-comments#198]
Framework/CMS 3.5.2 Comments release 2.1.3 and 2.1.2

I've installed commets via composer and added this to my config.yml file:
```
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Comments\Extensions\CommentsExtension
```
The comments tab shows up in the left column of the CMS, but no 'Behavior' or Comments tab on any of the pages.

I have also tried:
```
SiteTree:
  extensions:
    - CommentsExtension
```
and
```
BlogPost:
  extensions:
    - CommentsExtension
```
specifically. And all that does is put a comments grid on the blog post pages. But still no Behavior tab on that page.

**Comment by dhensby** [comment]
What is the "behaviour" tab? Should that be being added?

**Comment by digi-brains** [comment]
Doh! My bad. I meant to say that there was no controls showing up in any of the tabs, left column of the CMS or Setting tab on each page.

That said, after uninstalling and reinstalling twice it looks like the controls are now there. Weird. Sorry for jumping the gun. This is closed.
