### ISSUE TITLE
augmentSQL to join SiteTree causes ambiguous column ParentID error

### ISSUE THREAD

**Issue by jjjjjjjjjjjjjjjjjjjj** [silverstripe/silverstripe-comments#202]
I'm guessing this is a very narrow use case. 

Some background: we're using Subsites and want to filter out comments that don't belong to the current Subsite. This is naturally handled in the front end, but for the comments ModelAdmin we've resorted to using `augmentSQL`, joining `SiteTree` on `Comment.ParentID = SiteTree.ID` like so:

```PHP
# In an extension extending Comment...

public function augmentSQL(SQLQuery &$query)
{
    // Some code determining if a join is needed is removed for brevity. 
    $subsiteID = (int) Subsite::currentSubsiteID();
    $query->addLeftJoin('SiteTree', 'Comment.ParentID = SiteTree.ID');
    $query->addWhere('"SiteTree"."SubsiteID" IN (' . $subsiteID . ')');
}
```

Which leads to following `SS_DatabaseException`: `Column 'ParentID' in where clause is ambiguous`, because the `foreignKey` of `CommentList` is `ParentID` rather than `Comment.ParentID` (I'm guessing).

Updating the second argument of `parent::construct()` in the constructor of `CommentList` to following solves the problem, but looks a bit weird:

```PHP
# CommentList.php...

public function __construct($parentClassName)
{
    parent::__construct('Comment', 'Comment"."ParentID');
    // Rest is excluded for brevity.
}
```

Any thoughts on this?

**Comment by robbieaverill** [comment]
Related to https://github.com/silverstripe/silverstripe-subsites/pull/278?

**Comment by robbieaverill** [comment]
There's nothing wrong with being more explicit than is directly necessary when it comes to database queries - especially when it's not directly obvious in the use of the public API. Fancy putting in a pull request @janneklouman?

**Comment by janneklouman** [comment]
Sure thing! Sorry for the late reply.

**Comment by robbieaverill** [comment]
Oddly your example augmentSQL method filters correctly for me, without the error you're experiencing

**Comment by janneklouman** [comment]
Hmm, I just tried it with a clean installation (SS3.6 + Comments + Subsites) and I'm still getting the error.

I pushed the repo so you can try for yourself https://github.com/janneklouman/ss-comments-test

I appreciate all the feedback, but I feel like maybe you shouldn't put too much effort into this, definitely not for us. It seems like such a random scenario, and our problem can be solved without using augmentSQL (for example filtering the ModelAdmin).

**Comment by NightJar** [comment]
Personally I think this case is better suited for an Extension to the Administration interface. e.g. `CommentAdminExtension::updateEditForm`

You can then loop through each `GridField` instance, making an alteration such as:

```php
$subsiteID = (int) Subsite::currentSubsiteID();
// [...]
$list = $gridField->getList();
$gridField->setList(
    $list->filter('Parent.SubsiteID', $subsiteID)
);
```

Which should adjust the list for you without the need for complex manual adjustments - nor the need for tight coupling to subsites within this module's code :)

**Comment by robbieaverill** [comment]
I agree with @NightJar's suggestion here that it could be worked around in user code for specific lists, but I don't see any problem in making the SQL less ambiguous - it's not introducing any coupling by doing so.

**Comment by NightJar** [comment]
This is true. What I mean to say is that my impression is that SQL is always unambiguous when generated via e.g. `DataList` (through `DataQuery`). The crux of the issue here is that `where` and `leftJoin` are being used directly, which circumnavigates the routines for checking table names, etc.

Of course if it turns out to be because of the polymorphic nature of this 'relationship' (via `db` rather than `has_one` - and the use of `CommentList`), then that's a different story, for sure :)

**Comment by ScopeyNZ** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
