### ISSUE TITLE
Was SS3 compatability dropped?

### ISSUE THREAD

**Issue by mrgray** [silverstripe/silverstripe-comments#203]
Just noticed the requirements were upgraded to SS4; is it still compatible with 3?

**Comment by robbieaverill** [comment]
Hi @mrgray, the master branch is SS4 compatible now. You can use 2.1 or the 2.1.x tags for SS3 support. This module will continue to be supported for as long as SS3 is. Cheers!

**Comment by mrgray** [comment]
Thank you @robbieaverill!
