### ISSUE TITLE
Composer installation of comments fails for SS4.0.0-alpha7

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-comments#208]
After using `composer create-project silverstripe/installer testsite 4.0.0-alpha7` to install a fresh instance of SS, the command `composer require silverstripe/comments` gives the error:

Installation failed, reverting ./composer.json to its original content.

**Comment by dhensby** [comment]
What's the train it gives for failure?

**Comment by SpiritLevel** [comment]
Here is the full message, which I take it is what you mean by "train" :) If not, let me know what info you need. I just assumed this was a simple dependency issue so didn't provide it all...

Using version ^2.1 for silverstripe/comments
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - silverstripe/framework 3.5.x-dev requires php >=5.3.3,<7 -> your PHP version (7.0.18) does not satisfy that requirement.
    - Conclusion: remove silverstripe/framework 4.0.0-alpha7
    - Conclusion: don't install silverstripe/framework 4.0.0-alpha7
    - silverstripe/comments 2.1.x-dev requires silverstripe/framework ~3.1 -> satisfiable by silverstripe/framework[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/comments 2.1.4 requires silverstripe/framework ~3.1 -> satisfiable by silverstripe/framework[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/comments 2.1.3 requires silverstripe/framework ~3.1 -> satisfiable by silverstripe/framework[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/comments 2.1.2 requires silverstripe/framework ~3.1 -> satisfiable by silverstripe/framework[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/comments 2.1.1 requires silverstripe/framework ~3.1 -> satisfiable by silverstripe/framework[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - silverstripe/comments 2.1.0 requires silverstripe/framework ~3.1 -> satisfiable by silverstripe/framework[3.5.x-dev, 3.6.x-dev, 3.x-dev, 3.7.x-dev].
    - Can only install one of: silverstripe/framework[3.6.x-dev, 4.0.0-alpha7].
    - Can only install one of: silverstripe/framework[3.x-dev, 4.0.0-alpha7].
    - Can only install one of: silverstripe/framework[3.7.x-dev, 4.0.0-alpha7].
    - Installation request for silverstripe/framework 4.0.0-alpha7 -> satisfiable by silverstripe/framework[4.0.0-alpha7].
    - Installation request for silverstripe/comments ^2.1 -> satisfiable by silverstripe/comments[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.x-dev].


Installation failed, reverting ./composer.json to its original content.

**Comment by dhensby** [comment]
2.1 is 3.x compatible verson - you need to use 3.x-dev
