### ISSUE TITLE
Update "spam", "approved" etc buttons

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-comments#223]
When reviewing comments in the admin area, the "Spam", "Approve" buttons etc look odd and should be updated.

We can either switch for small Bootstrap buttons, or use an icon of some sort, e.g.:

![image](https://user-images.githubusercontent.com/5170590/33908006-e4a86fda-dfeb-11e7-9cc3-2289712b41ef.png)

![image](https://user-images.githubusercontent.com/5170590/33908119-36adc712-dfec-11e7-9459-4bebe7885a11.png)

cc @sachajudd @clarkepaul

**Comment by clarkepaul** [comment]
These actions will be replaced with a single "more options" dropdown which will hold text based actions so spam will make sense in that context. It could even be changed to "Mark as spam" once the dropdown is available.

**Comment by sachajudd** [comment]
In the meantime a small Bootstrap secondary button is fine 🙂

**Comment by robbieaverill** [comment]
This is one option that seems to work OK (not using an icon)

![image](https://user-images.githubusercontent.com/5170590/33922185-dd8acaf8-e02d-11e7-907f-5a73dc1124b9.png)

**Comment by sachajudd** [comment]
Looks good, do you mind sharing a BS button screenshot? 🙂

**Comment by sachajudd** [comment]
Discussed with @robbieaverill to leave as text in the gridfield for future purposes.

**Comment by robbieaverill** [comment]
PR at #224
