### ISSUE TITLE
Server error when click on Comments tab in CMS

### ISSUE THREAD

**Issue by buffy999** [silverstripe/silverstripe-comments#229]
I installed the Comments module as expected, and also added the codes into xml file, and then dev/build. I'm using the Comment's master version with the SS 4.0.3.

I don't know why i'm getting server error when i click on Comments tab in CMS. Any thoughts to what i did wrong?

**In mysite.xml file:**
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Comments\Extensions\CommentsExtension
  comments:
    enabled: true # Enables commenting to be disabled for a specific class (or subclass of a parent with commenting enabled)
    enabled_cms: false # The 'enabled' option will be set via the CMS instead of config
    require_login: false # boolean, whether a user needs to login
    require_login_cms: false # The 'require_login' option will be set via the CMS instead of config
    required_permission: false # required permission to comment (or array of permissions)
    include_js: true # Enhance operation by ajax behaviour on moderation links
    use_gravatar: false # set to true to show gravatar icons,
    gravatar_size: 80 # size of gravatar in pixels.  This is the same as the standard default
    gravatar_default: 'identicon' # theme for 'not found' gravatar (see http://gravatar.com/site/implement/images/)
    gravatar_rating: 'g' # gravatar rating. This is the same as the standard default
    show_comments_when_disabled: false # when comments are disabled should we show older comments (if available)
    order_comments_by: '"Created" DESC'
    comments_per_page: 10
    comments_holder_id: 'comments-holder' # id for the comments holder
    comment_permalink_prefix: 'comment-' # id prefix for each comment. If needed make this different
    require_moderation: false
    require_moderation_nonmembers: false # requires moderation for comments posted by non-members. 'require_moderation' overrides this if set.
    require_moderation_cms: false # If true, ignore above values and configure moderation requirements via the CMS only
    frontend_moderation: false # Display unmoderated comments in the frontend, if the user can moderate them.
    frontend_spam: false # Display spam comments in the frontend, if the user can moderate them.
    html_allowed: false # allow for sanitized HTML in comments
    html_allowed_elements:
      - a
      - img
      - i
      - b
    use_preview: false # preview formatted comment (when allowing HTML). Requires include_js=true
    nested_comments: false # If true comments can be replied to up to nested_depth levels
    nested_depth: 2 # The maximum depth of the comment hierarchy for comment reply purposes

**Comment by andrewandante** [comment]
Hi @buffy999 - can I just confirm that you are using a `.yml` file, not a `.xml` file?

**Comment by buffy999** [comment]
Ahh sorry yes i meant .yml file, sorry for my typo

**Comment by andrewandante** [comment]
No worries - and this file is `mysite/_config/mysite.yml`? And once you have made these changes, you have run a flush?

**Comment by buffy999** [comment]
Yes that's what i did, still getting server error when clicking on Comments tab

**Comment by andrewandante** [comment]
OK, I will try and reproduce. Can you try and get a more specific error than "Server Error"? Make sure you are in `dev` mode and check your logs for anything that might help, thanks!

**Comment by andrewandante** [comment]
Alright, I've installed the module on my own project with the config above and encountered no problems. The only things I can think of are either a) there's some custom code in your project that is causing the error or b) your `.yml` file is formatted incorrectly (it should have spaces, not tabs, for example).

As the bug is not reproducible I'm going to close this up, I'd recommend signing up to the [Slack Channel](https://www.silverstripe.org/community/slack-signup/) if you haven't already and asking for help debugging in there, as it doesn't appear to be an issue with the module per se.

Thanks for raising the issue and I hope you find the answer you need! Good luck!
