### ISSUE TITLE
Update to match colymba/GridFieldBulkEditingTools changes

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-comments#231]
Bringing in CWP 2.0.0-rc1, I cannot edit a page in the CMS. The error thrown is:

```
PHP Fatal error:  Bulk action handler not found:  in /sites/smalltest2/releases/20180223155356/vendor/colymba/gridfield-bulk-editing-tools/src/BulkManager/BulkManager.php on line 113
```

This is because the `addBulkAction()` method has a totally different implementation with the version pulled in with the recipe, that is SS4 compatible. Basically, [this whole section](https://github.com/silverstripe/silverstripe-comments/blob/master/src/Admin/CommentsGridFieldConfig.php) needs to be rewritten

To reproduce:

1) install CWP recipe 2.0.0-rc1
2) once you've hacked around with `composer.json` to pull in the up-to-date version of `colymba/gridfield-bulk-editing-tools`, visit `admin/pages` section
3) click on any page to edit it, you will get an Internal Server Error

**Comment by robbieaverill** [comment]
Looks like we might need to implement concrete classes for "spam" and "approve" actions rather than using the base Handler with configuration options - it doesn't look like the module supports that any more. @colymba are you able to confirm, or provide any extra info for us on this? Thanks =)

**Comment by colymba** [comment]
@robbieaverill what you did in the PR is what I would have done.
The whole addBulkAction/Handler API changed, it was long overdue and should make things cleaner in the future... I hope.

For now each bulk action need a different handler. I had thoughts that one Handler could take are of multiple actions (hence the action param https://github.com/colymba/GridFieldBulkEditingTools/blob/master/src/BulkManager/BulkManager.php#L110) but it hasn't been implemented and might now be.

So for now, one Handler per action and all configs are on the Handler class. Just like you did.

**Comment by robbieaverill** [comment]
Ok great, thanks for the feedback!
