### ISSUE TITLE
Fatal error: Bulk action handler not found: spam

### ISSUE THREAD

**Issue by digi-brains** [silverstripe/silverstripe-comments#233]
After installing the comments module, which in turn installs this module; after a dev/build, clicking on any page in the cms results in this error.
```
[User Error] Bulk action handler not found: spam GET /admin/pages/edit/show/1 Line 126 in /var/www/html/.../vendor/colymba/gridfield-bulk-editing-tools/src/BulkManager/BulkManager.php
```
**composer.json**
"silverstripe/comments" : "3.0.0"
"silverstripe/spamprotection" : "3.0.0"
"undefinedoffset/silverstripe-nocaptcha" : "2.0.0-alpha2"

**config.yml**
SilverStripe\Blog\Model\Blog:
  extensions:
    - SilverStripe\Widgets\Extensions\WidgetPageExtension

SilverStripe\Blog\Model\BlogPost:
  extensions:
    - SilverStripe\Comments\Extensions\CommentsExtension
  comments:
    enabled: true
    require_moderation: true

SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
    default_spam_protector: UndefinedOffset\NoCaptcha\Forms\NocaptchaProtector

**Comment by andrewandante** [comment]
Hi @digi-brains , this has been raised and closed here: https://github.com/silverstripe/silverstripe-comments/issues/231 - thanks!

**Comment by digi-brains** [comment]
Sorry I don't understand. The issue exists, but it's closed?

**Comment by andrewandante** [comment]
Yes, because it has been fixed! You'll need to pull in a version that contains the PR https://github.com/silverstripe/silverstripe-comments/pull/232 that introduced the fix. At the moment that is dev-master or possibly 3.x-dev, you'll have to do a bit of exploring.

**Comment by digi-brains** [comment]
Ah, thank you for the clarification.
