### ISSUE TITLE
BulkTools now expect all responses to be HTTPBulkToolsResponse

### ISSUE THREAD

**Issue by colymba** [silverstripe/silverstripe-comments#241]
A quick heads up... The latest version of https://github.com/colymba/GridFieldBulkEditingTools has introduced a common response format for all bulk tools via the new `HTTPBulkToolsResponse`. The API should not be changing much anymore, although it is still in beta...

This implies only a very little change, mainly https://github.com/silverstripe/silverstripe-comments/blob/master/src/Admin/CommentsGridFieldBulkAction/CommentHandler.php#L30 should now use `HTTPBulkToolsResponse`, then use either `addSuccessRecord($record)` or `addFailedRecord($record, $message)` depending if `$this->updateComment($comment);` worked or not.

**Comment by robbieaverill** [comment]
Thanks for the heads up @colymba. This could be tricky, since we've tagged comments as stable already with a `^3.0` constraint on GridFieldBulkEditingTools. We may have to work around this as necessary and update handling as a patch semver fix (even if it breaks semver) when your module is stable in this release line.

**Comment by colymba** [comment]
Sorry I've been making a lot of API changes in the module lately... it just needed some long overdue love and updates... @robbieaverill I guess changing the response format would be considered a minor change for semver...
but even if this is not patched immediately, the core functionality should still be working anyway, it probably will just through a lot of error in the browser console...

**Comment by robbieaverill** [comment]
No problem @colymba, we will handle the changes as needed from this end!

FYI we've stabilised the blog and comments modules already so people will be starting to use them. We can always lock against a beta tag in the interim, but it'd be great if you could give a day or two warning before tagging stable incase it breaks things for users (we're using a stable compatible composer constraint for your module).

**Comment by robbieaverill** [comment]
Hey @colymba, how far away to you think this module is from being stable?

**Comment by colymba** [comment]
@robbieaverill I haven't had much time lately, but for now, the only thing that needs fixing for now is that nested gridfield issue (https://github.com/colymba/GridFieldBulkEditingTools/issues/174). After that am happy to put out a stable tag.

**Comment by robbieaverill** [comment]
cc @Cheddam
