### ISSUE TITLE
Comments not requiring moderation

### ISSUE THREAD

**Issue by digi-brains** [silverstripe/silverstripe-comments#246]
SilverStripe 4.1.0
Blog 3.0.0
Comments 3.1.0

I've added Comments to my site via config.yml like this:

```
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Comments\Extensions\CommentsExtension

SilverStripe\Blog\Model\BlogPost:
  comments:
    require_moderation: true
```

After leaving a comment while logged out my comment is automatically approved and no moderation is required.
![screenshot-trotter-2018 04 12-15-45-17](https://user-images.githubusercontent.com/598105/38707997-e1d20c9a-3e68-11e8-9b6d-842709d61b48.png)

**Comment by andrewandante** [comment]
Seems related to #242 - closing as a duplicate. Feel free to re-open if it's not :)
