### ISSUE TITLE
Have the JS URL validator validate valid URLs

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-comments#272]
At current a valid (although not necessarily _complete_) URL will be shown as invalid
![image](https://user-images.githubusercontent.com/778003/51001613-69273b80-1595-11e9-97a1-998380096b7f.png)

However adding a protocol to it will see the validation pass
![image](https://user-images.githubusercontent.com/778003/51001641-7b08de80-1595-11e9-9e99-5888910ddbb2.png)

This issue only affects the JavaScript validator - disabling JavaScript and then submitting the form sees a successful submission (although in this case I feel that any value may be valid - although that should be a separate issue _if true_).

**Comment by NightJar** [comment]
The quickest solution is to upgrade the validation library, as this is fixed in the most recent version (at least):
https://github.com/jquery-validation/jquery-validation/blob/a9c20ec280ce3a968abbca5611dcd63f412b5d34/src/core.js#L1408

**Comment by NightJar** [comment]
OK that theory held untrue, but none the less updating is never a bad idea so #275 updates [jQuery.validator](https://github.com/jquery-validation/jquery-validation/releases/tag/1.19.0)

**Comment by NightJar** [comment]
It's done, justification in the commit message. #276

**Comment by ScopeyNZ** [comment]
Closed in #276
