### ISSUE TITLE
frontend_moderation: false doesn't seem to do anything

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-comments#282]
**Comments 3.2.x-dev**

If you change CommentsExtension default values for frontend_moderation, frontend_spam to true or false and flush, the frontend doesn't change.

I presume these were supposed to control whether the moderation controls are displayed on the frontend - if that's the case it no longer works as it was designed to.

**Comment by NightJar** [comment]
Cannot reproduce.

The default setup is `require_moderation: false` - all comments made are instantly and forever surpassing the `frontend_moderation` setting. Setting `require_moderation` to true and making a new comment - it does not show under the default settings on the front-end. Enabling `frontend_moderation` allows it to show.

"Rejecting" a comment is an alias for "delete forever", not "unapprove". It does not revert a comment from `Approved` to `New`.

`frontend_spam` also works as intended. After clicking `Spam it` the comment disappears from the front-end (again the default is `false`).
Enabling `frontend_spam` makes it appear again.

The `frontend_moderation` name is also a bit of a misnomer. It allows the front-end management of `New` comments, not the overall moderation of comments (in whatever state). An admin can always moderate (delete or set as spam) `Approved` comments, which is the state all comments are in by default.
