### ISSUE TITLE
BUG CommentAdmin permission not available in Permissions tab

### ISSUE THREAD

**Issue by muskie9** [silverstripe/silverstripe-comments#288]
It seams that not implementing `PermissionProvider` prevents allowing the `CMS_ACCESS_CommentAdmin` permission from being applied to Groups or Roles.

**Comment by robbieaverill** [comment]
Could you clarify a little more what your problem is here? CommendAdmin extends LeftAndMain, which implements PermissionProvider.

**Comment by muskie9** [comment]
Version: 3.2.0

When I go to the Permissions tab on a group (if not specifying the `implements PermissionProvider` on CommentAdmin), I don't seem to have the "Access to 'Comments' section" option:

**Without the implements declaration on CommentAdmin**
![Screen+Shot+2019-06-27+at+5 15 26+PM](https://user-images.githubusercontent.com/870751/60304535-57e1a980-98ff-11e9-9069-825646a2168c.png)


**With the implements declaration on CommentAdmin**
![Screen+Shot+2019-06-27+at+5 16 10+PM](https://user-images.githubusercontent.com/870751/60304550-65972f00-98ff-11e9-9c8c-f35e6949247f.png)

**Comment by robbieaverill** [comment]
Sounds like some strange LSB interface checking bug. Thanks for the update!
