### ISSUE TITLE
Docs missing information about $CommentsForm Tag

### ISSUE THREAD

**Issue by qunabu** [silverstripe/silverstripe-comments#293]
The tag `$CommentsForm` is included in the default `simple` theme of SS but for other is missing. I think there should be information in the installation documentation https://github.com/silverstripe/silverstripe-comments/blob/master/docs/en/Installing.md that `$CommentsForm` must be placed somewhere in the themes to make this module work as intended.

**Comment by NightJar** [comment]
Sounds like a great idea. Would you like to submit a pull request to resolve this, and help enhance the project for new users?

**Comment by AdamSawoscianik** [comment]
Hello, I have created a new pull request for this issue:

https://github.com/silverstripe/silverstripe-comments/pull/294

**Comment by NightJar** [comment]
That's great, thank you!
