### ISSUE TITLE
action checkboxes broken

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-comments#300]
the class ```.form-check-input``` should not be absolute. See these screenshots using firefox:

![image](https://user-images.githubusercontent.com/67215/79529670-574e1580-80c1-11ea-98cb-a88bb52c7835.png)

scrolling down :
![image](https://user-images.githubusercontent.com/67215/79529695-73ea4d80-80c1-11ea-86ad-ddec50dd4b4b.png)

on chrome there might be something more going on, as the checkboxes don't even show:

![image](https://user-images.githubusercontent.com/67215/79529761-9aa88400-80c1-11ea-8f8b-88b1daaeb62c.png)

**Comment by dhensby** [comment]
Please consider raising a PR to fix this

**Comment by emteknetnz** [comment]
I've tested and merged the linked PR.  Thanks for contributing.
