### ISSUE TITLE
CommentsExtension->canPost is deprecated

### ISSUE THREAD

**Issue by hp7** [silverstripe/silverstripe-comments#310]
SS 3.7.x
ERROR: [User Deprecated] CommentsExtension->canPost is deprecated. Use canPostComment instead. Called from Object->__call

>203 			$level = self::$notice_level;
204 			if (!$level) $level = E_USER_DEPRECATED;
205 
206 			// Then raise the notice
207 			if(substr($string,-1) != '.') $string .= ".";
208 
209 			$string .= " Called from " . self::get_called_method_from_trace($backtrace, 2) . '.';
210 
211 			if($caller) {
**_212_** 				**user_error($caller.' is deprecated.'.($string ? ' '.$string : ''), $level);**
213 			} else {
214 				user_error($string, $level);
215 			}
216 
217 		}
218 	}

**Comment by dnsl48** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The report you provided is missing some valuable details.
Please follow the guide about what is useful when making [bug reports](https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/).

**Comment by emteknetnz** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
