### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [silverstripe/silverstripe-comments#327]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by michalkleiner** [comment]
Hi @JamieSlome,
the guidance around issues reporting within the Silverstripe CMS (and related modules) is in the documentation on https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/#reporting-security-issues.

**Comment by michalkleiner** [comment]
We will consider adding a SECURITY.md file across all supported Silverstripe CMS modules separately, thank you for the suggestion. I'll close this issue for now as this needs to be addressed globally, not just in this module.
