### ISSUE TITLE
Can't display $CommentsForm for DataObjects

### ISSUE THREAD

**Issue by digitweaks** [silverstripe/silverstripe-comments#347]
Hi there,

I’ve extended a PostObject which is a simple DataObject and I can see fields created in the database. When I use the $CommentsForm it displays properly on the pages of SiteTree like the homepage, but it doesn’t show anything for PostObject. There’s nothing special indicated in the documentation so can’t tell if there’s something to do. PostObjects have the Comments tab in the back end, they provide comments but nothing on the front end, the form doesn’t appear for PostObject

**Comment by Digitweaks** [comment]
Seems that the ParentClass enum doesn't include the DataObject class

**Comment by Digitweaks** [comment]
Any help, I tried everything to get this working but there's no example for DataObjects and it's honestly a shame, I lost already two evenings on this.

**Comment by digitweaks** [comment]
Ok, so I had found a hacky solution but ntd from the official SilverStripe forum gave me the right solution. I just had a exists() function that was returning false instead of true. Here is the solution in case you have the same issue.

https://forum.silverstripe.org/t/commentsform-doesnt-show-for-dataobjects/5500

// In CommentsExtension.php
if (!$this->owner->exists()) {
    return false;
}

// In DataObject.php
public function exists()
{
    return (isset($this->record['ID']) && $this->record['ID'] > 0);
}
