### ISSUE TITLE
how to remove "email" and "website" inputs from comment form

### ISSUE THREAD

**Issue by korneliusz-w** [silverstripe/silverstripe-comments#384]
I would like to remove "email" and "website" inputs from comment form. How to do that? Why this field are shown?
Also I don't need RSS link in footer, how to remove them?

**Comment by michalkleiner** [comment]
Hi @korneliusz-w. Thanks for opening the issue. The issue tracker is mostly used for raising bugs or suggesting enhancements. For questions like this please use one of the [channels listed in the documentation](https://docs.silverstripe.org/en/5/#getting-support). Best bet is to ask your question on [Slack](https://www.silverstripe.org/community/slack-signup/).
