### ISSUE TITLE
comments shall utilize the memberprofiles module, if present

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-comments#6]
Copied from http://open.silverstripe.org/ticket/6823

Each comment shall display the name of the user who wrote it;

 * Already implemented as long as the memberprofiles module overloads Name

The name of the user shall be a link to its memberprofile, if the memberprofiles module present;
The link shall not be readable by robots in order to avoid spam.

 * Good point, currently it shows a link if the user fills in their website URL, but adding a Link() fallback to the template is easy

Should the memberprofiles module be missing, then there shall be a field for the address of the user in the comments form.
In SS2 this was the URL field, but this field should allow addresses of any kind, such as webpage URL, E-Mail address, ICQ address, ...);

 * The module allows email, url (2.* didn't have email) and you can easily extend it to support twitter (as per the silverstripe.org blog). Will probably want to document how this is done rather than providing all the options built in. Off topic but posting via facebook connect / twitter oauth could be an fun project for someone.

The address of the user shall be a link under its name. The link shall not be readable by robots in order to avoid spam.
The author of a DataObject (Page, BlogEntry, ...) shall specify on the back-end CMS whether a user can add
one comment only;
unlimited comments.

 * Interesting use case, but I don't think it's common enough to require it to be an option for every site? How would it uniquely identify a 'person' who wasn't logged in? Email address perhaps? but then to get around it you could use  will+01@gmail.com,  will+02@gmail.com which isn't entirely foolproof.

If a user unregisters from the website, he/she shall be asked whether its comments should be removed from the website;
If the user specifies to retain its comments, he/she shall be asked if his/her address shall be made available as a link under its name in the comments.

 *  That would be a feature of the memberprofiles module and not the comments module so you'll need to submit an enhancement request on the issue tracker for memberprofiles (github).

**Comment by assertchris** [comment]
@sminnee Do we still require this level of detail? Names are displayed with comments (provided the templates still do this).

**Comment by tractorcow** [comment]
No one has picked this up in a few years. Can we close this?

**Comment by wilr** [comment]
+1 for closing. I don't think it's important.
