### ISSUE TITLE
Option to remove moderated spam from the front end

### ISSUE THREAD

**Issue by room9** [silverstripe/silverstripe-comments#85]
If the admin is logged in and reviewing the comments for a page they will see all comments including moderated spam. This can result in many pages of spam when the bulk of it has already been dealt with. I think administrators might prefer to only see valid comments and unmoderated comments and hide those comments already marked as spam. This does remove the ability to unmark them as spam, but that ability would still exist in the CommentAdmin in the CMS.

**Comment by assertchris** [comment]
I think this is achieved with the recent work to the module. @tractorcow can you confirm?

**Comment by tractorcow** [comment]
This has been fixed; Now you can optionally toggle frontend_moderation or frontend_spam to turn on or off the display of these comments.
