### ISSUE TITLE
Unable to Override Single Comment Template with AJAX in a Theme

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-comments#91]
In order to change the layout of comments on my site, I've added a template CommentsInterface_singlecomment.ss to my theme.  This works when rendering a new page view but when I try to render a comment via AJAX, the template file in the comments module is used instead.  This leads to inconsistency in the layout.

**Comment by wilr** [comment]
Where is your template located? Are you using any custom logic to select your theme?

**Comment by gordonbanderson** [comment]
hi Will
No custom logic regarding theme selection.  Location of override in my theme, which works for non AJAX requests, is 
```
./themes/wot/templates/CommentsInterface_singlecomment.ss
```
In the module it is at
```
./comments/templates/CommentsInterface_singlecomment.ss
```

**Comment by assertchris** [comment]
Are you still seeing this issue?

**Comment by gordonbanderson** [comment]
I will test with the latest codebase and get back to you

**Comment by tractorcow** [comment]
@gordonbanderson any update on this issue?

**Comment by gordonbanderson** [comment]
I tested this yesterday and this is no longer broken
