### ISSUE TITLE
CommentingController::CommentsForm takes on far too much responsibility

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-comments#95]
The `CommentsForm` method does a lot of work that is beyond the scope of the function.

This needs to be split into component parts for easier overloading as well as consistent use of the `::create()` syntax.

**Comment by assertchris** [comment]
@tractorcow / @sminnee see this

**Comment by tractorcow** [comment]
I'll see if we can fix this in the nested comments update. :)

**Comment by dhensby** [comment]
@tractorcow did this get fixed as part of nested comments update

**Comment by tractorcow** [comment]
Nope! :D

**Comment by gordonbanderson** [comment]
:)

**Comment by robbieaverill** [comment]
💯  on this. [Scrutinizer agrees too](https://scrutinizer-ci.com/g/silverstripe/silverstripe-comments/code-structure/master/operation/%2Bglobal%5CCommentingController%3A%3ACommentsForm), while it's not quite as bad as [`doPostComment`](https://scrutinizer-ci.com/g/silverstripe/silverstripe-comments/code-structure/master/operation/%2Bglobal%5CCommentingController%3A%3AdoPostComment)...

**Comment by lozcalver** [comment]
Fixed now:

https://github.com/silverstripe/silverstripe-comments/blob/066b28bb3d374356746e1ea7727000e65d0644d5/src/Controllers/CommentingController.php#L485-L493
